# Site
name: "Decision Ninja Blog"
title: "Decision Ninja"
description: "Tools, tips, and tricks to improve the quality of all your personal and professional decisions."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: /mediumish-theme-jekyll
google_analytics: 'G-8JMR386WRC'
#disqus: 'demowebsite'
mailchimp-list: 'https://gmail.us14.list-manage.com/subscribe/post?u=7a512c3d139663fb4c4cbab0c&amp;id=a4d9805898'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  rutul:
    name: Rutul
    display_name: Rutul Davé
    # avatar: 'assets/images/avatar.png'
    gravatar: 70edbf7710b860f29d6ab7f3f32cfb87
    email: rutuldave@gmail.com
    web: https://rutuldave.com
    twitter: https://twitter.com/letsfixtheworld
    description: "I am an entrepreneur who loves making products and growing startups. I spend most of my time at the intersection of business, technology, and finance."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
